
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABRE_PARENTESES AND ARRAY ASPAS ATRIBUICAO BOOLEAN CHAR COMECO_DELIMITADOR_CHAVES DIFERENCA DIFERENTE DIVISAO DOUBLE DOUBLEAND_BITWISE DOUBLEOR_BITWISE ELSE ENTRADA FECHA_PARENTESES FIM FINAL_DELIMITADOR_CHAVES IF IGNORE IGUAL INICIA_COLCHETES INICIO INT INTERSECCAO LITERAL MAIOR MAIOR_OU_IGUAL MAIS MATRIZ MENOR MENOR_OU_IGUAL MENOS MODULO MULTIPLICACAO NOT OR PONTO PONTO_E_VIRGULA PREMISSA PRODUTO_CARTESIANO PROJECAO SAIDA SELECAO TERMINA_COLCHETES TILNOT_BITWISE TIPO_ARRAY TIPO_BOOLEAN TIPO_CHAR TIPO_DOUBLE TIPO_INT TIPO_LITERAL TIPO_MATRIZ TIPO_PREMISSA UNIAO VIRGULA WHILE literal_mf numero_mfempty :end : PONTO_E_VIRGULAstatement    : if_statement\n    list_statement : statement list_statement\n                      | empty\n    statement : INICIO COMECO_DELIMITADOR_CHAVES list_statement FINAL_DELIMITADOR_CHAVES FIM\n    \n    comparacao :\n    if_statement : IF ABRE_PARENTESES comparacao FECHA_PARENTESES COMECO_DELIMITADOR_CHAVES list_statement FINAL_DELIMITADOR_CHAVES\n                    | IF ABRE_PARENTESES comparacao FECHA_PARENTESES COMECO_DELIMITADOR_CHAVES list_statement FINAL_DELIMITADOR_CHAVES ELSE COMECO_DELIMITADOR_CHAVES list_statement FINAL_DELIMITADOR_CHAVES\n    while_statement : ABRE_PARENTESES comparacao FECHA_PARENTESES COMECO_DELIMITADOR_CHAVES list_statement FINAL_DELIMITADOR_CHAVES\n    '
    
_lr_action_items = {'$end':([0,1,],[-1,0,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'empty':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> empty","S'",1,None,None,None),
  ('empty -> <empty>','empty',0,'p_empty','main.py',213),
  ('end -> PONTO_E_VIRGULA','end',1,'p_define_end_of_instruction','main.py',217),
  ('statement -> if_statement','statement',1,'p_statement','main.py',220),
  ('list_statement -> statement list_statement','list_statement',2,'p_list_statement','main.py',229),
  ('list_statement -> empty','list_statement',1,'p_list_statement','main.py',230),
  ('statement -> INICIO COMECO_DELIMITADOR_CHAVES list_statement FINAL_DELIMITADOR_CHAVES FIM','statement',5,'p_statement_source','main.py',234),
  ('comparacao -> <empty>','comparacao',0,'p_statement_comparacao','main.py',239),
  ('if_statement -> IF ABRE_PARENTESES comparacao FECHA_PARENTESES COMECO_DELIMITADOR_CHAVES list_statement FINAL_DELIMITADOR_CHAVES','if_statement',7,'p_statement_if','main.py',244),
  ('if_statement -> IF ABRE_PARENTESES comparacao FECHA_PARENTESES COMECO_DELIMITADOR_CHAVES list_statement FINAL_DELIMITADOR_CHAVES ELSE COMECO_DELIMITADOR_CHAVES list_statement FINAL_DELIMITADOR_CHAVES','if_statement',11,'p_statement_if','main.py',245),
  ('while_statement -> ABRE_PARENTESES comparacao FECHA_PARENTESES COMECO_DELIMITADOR_CHAVES list_statement FINAL_DELIMITADOR_CHAVES','while_statement',6,'p_statement_while','main.py',254),
]
